version: 2
jobs:
  build:
    docker:
      - image: fedora:latest
    working_directory: ~/Authenticator
    steps:
      - run:
          name: Install dependencies
          command: dnf -y install flatpak flatpak-builder iputils
      - checkout
      - run: flatpak-builder install com.github.bilelmoussaoui.Authenticator.json --force-clean
